os: linux
language: php

env:
  global:
    - secure: "Vbdts9k+dvnzAmuRPXMDZLw2+s+4q0Ijdbx97rCBefrBbG+6elfR0ao60135QVAoiQxTR//Iz6ZZbsFfTTt9Qo4SVvulzepuLz4lDQmO1BTeKlAWyM650+uFDP39iRY+i6Z7w5RGZzw4F3Sjw8N4kcxdrkkJLH4p9ZQkA5uSkzg="

jobs:
  fast_finish: true
  include:
    - php: 5.5 # PHPUnit 4.8
      dist: trusty
    - php: 5.6 # PHPUnit 5.7
      env: WITH_CS=true
    - php: 7 # PHPUnit 6.x
    - php: 7.1 # PHPUnit 7.x
    - php: 7.2 # PHPUnit 7.x
    - php: 7.3 # PHPUnit 7.x
    - php: hhvm-3.30 # PHPUnit 5.7
      dist: trusty
      env:
        - SKIP_LINT_TEST_CASES=1
        - USE_HHVM=true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ -z "$USE_HHVM" || "$USE_HHVM" != "true" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - if [[ -z "$USE_HHVM" || "$USE_HHVM" != "true" ]] && [[ "$GITHUB_TOKEN" != "" ]]; then composer config github-oauth.github.com $GITHUB_TOKEN; fi
  - composer validate

install:
  - if [[ "$USE_HHVM" == "true" ]]; then composer require --dev phpunit/phpunit ^5.7; fi # hhvm and phpunit 7 are incompatible
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit test
  - if [[ "$WITH_CS" == "true" ]]; then vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b78839c0066e95e47dab
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: never
